### ISSUE TITLE
Mob TargetGoal range does not change when not set before spawning, breaking the initial targeting of enemies

### ISSUE THREAD

**Issue by AKL55** [Sindarin27/Farsighted-Mobs#1]
![farsight](https://user-images.githubusercontent.com/89634553/131099895-5e5173bc-5929-4c3d-98a8-661d7ecab6b6.png)
![farsight2](https://user-images.githubusercontent.com/89634553/131100728-9a62deb2-7b4a-4569-8c56-d36a123ee0fb.png)

Tried both forge and fabric.

**Comment by Sindarin27** [comment]
Hi Arkile, thanks for the issue! Could you copy your latest.log for both to pastebin and send the link as well?

**Comment by AKL55** [comment]
[removed to declutter thread]

**Comment by Sindarin27** [comment]
Hmm, odd. I don't see any obvious failure messages. How did you test the mob's range? Remember that mobs don't instantly target the player, but can take several seconds to find you.
After the weekend, I'll be able to test your config files as well if the issue still persists.

**Comment by AKL55** [comment]
Ok.Thanks.i'm gonna try again.I was running and standing still in a range of 50 blocks then,i changed the default range to 1000 and nothing happend too.

**Comment by Sindarin27** [comment]
A bit of testing and I might have figured out the problem. Both versions of the mod only affect creatures that are newly spawned in the world. As such, if you change the config value and check the same monsters again, there will be no difference. Let me know if that could be the issue.

**Comment by Sindarin27** [comment]
After more extensive testing, I managed to find the same problem! This appears to be a bug in Minecraft itself: [MC-145656](https://bugs.mojang.com/browse/MC-145656).

What happens here: When a mob is spawned, its follow range is set to the value in the config after spawning. At this moment, the target range in TargetGoal is already set, and will not change. Reloading the world (or possibly even the chunk containing the mob) will fix this. 
On fabric, the default follow range for a mob will also be set before it enters the world, so the default range there is working fine.

I will attempt to fix this bug as soon as possible.

**Comment by Sindarin27** [comment]
Fixed in version 1.1 🥳
