### ISSUE TITLE
Configuration option for view distance

### ISSUE THREAD

**Issue by MinecraftPublisher** [Sindarin27/Farsighted-Mobs#5]
There should be a configuration option somewhere in the menu to allow for changing the amount of blocks the mobs can see. This could either  be done using another mod menu mod or your own button somewhere in the settings.

**Comment by Sindarin27** [comment]
Will likely not be implemented, due to the next version using datapacks for configuration instead.

**Comment by MinecraftPublisher** [comment]
ah, well nice
