### ISSUE TITLE
Can you do a release for 19.2?

### ISSUE THREAD

**Issue by szekelymatyas** [Sindarin27/Farsighted-Mobs#6]
While I'm confident that the 19.1 version is working for 19.2, modloaders doesn't seem to have this confidence. Meanwhile, I'm also sure that I can add it manually, but personally I don't like to stick with this kind of solution. I'm almost certain that you only need to change the version number and make a release, but if not I would still like to see an 19.2 version of this mod.

Thanks for the help in forward!

**Comment by Sindarin27** [comment]
Huh, I thought I handled this some time ago. I'll get on it ASAP!

**Comment by Sindarin27** [comment]
As it turns out, the mod itself should already work on 1.19.2. It's only CurseForge that thinks any differently. Changed the current release to explicitly support 1.19.2 as well, but let me know if there are any problems with it!
