### ISSUE TITLE
modrinth please :)

### ISSUE THREAD

**Issue by SylisMC** [Sindarin27/Farsighted-Mobs#8]
![image](https://github.com/Sindarin27/farsighted-mobs-fabric/assets/19602662/1553baab-7c08-4ee1-aa96-40240531a08e)

**Comment by SylisMC** [comment]
love the mod.  goes great with [Dusk](https://www.curseforge.com/minecraft/mc-mods/dusk) I am however a modrinth user, so easy updates would be mint

**Comment by Sindarin27** [comment]
After the mod's rework, both mods now use the same Modrinth page: https://modrinth.com/mod/farsighted-mobs
