### ISSUE TITLE
Add recent Fabric releases to Modrinth page

### ISSUE THREAD

**Issue by anoomolu** [Sindarin27/Farsighted-Mobs#9]
Hiya!

I really liked using this mod on 1.20.1, and wasn't aware that there were Fabric 1.21 releases available since I was only looking at the Modrinth page, which is my bad 😭 

If it's not too much of a hassle, would you be able to publish the newer releases that are available on CF, on Modrinth too? Thank you!

**Comment by Sindarin27** [comment]
Modrinth still has not approved my fabric version of the project. If this continues, I'll see if I can put both forge and fabric on the same page regardless of their differences.

**Comment by anoomolu** [comment]
Oh that’s odd, hope they get round to it soon ^^

**Comment by Sindarin27** [comment]
After the mod's rework, both mods now use the same Modrinth page: https://modrinth.com/mod/farsighted-mobs

**Comment by ihymyly** [comment]
Hey I know this is a closed issue now, but could you consider adding the 1.20.1 Fabric version on modrinth as well?

**Comment by Sindarin27** [comment]
Done!
